optimizer: {
  type: AdamW,
  kwargs: {
  lr: 0.001,
  weight_decay: 0.05}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 400,
    initial_epochs: 10}}

dataset : {
  train: { _base_: cfgs/dataset_configs/ShapeNet-55.yaml,
           others: { subset: 'train', npoints: 2048}},
  val : { _base_: cfgs/dataset_configs/ModelNet40.yaml,
            others: {subset: 'test', npoints: 1024}},
  extra_train : { _base_: cfgs/dataset_configs/ModelNet40.yaml,
            others: {subset: 'train'}},
  test : { _base_: cfgs/dataset_configs/ShapeNet-55.yaml,
            others: {subset: 'test', npoints: 2048}}}

model: {
  NAME: Point_UMAE,
  mask_ratio: 0.75,
  # tokenizers
  group_sizes: [32, 8, 4],
  num_groups: [128, 64, 32],
  # u-encoder
  encoder_depths: [2, 2, 2, 2, 2],
  encoder_dims: [384, 576, 768, 576, 384],
  encoder_up_block: 1,
  # decoder
  decoder_depth: 2,
  # others
  drop_path_rate: 0.1,
  num_heads: 6,
  loss_type: 'cdl2'}

npoints: 2048
total_bs: 256
step_per_update: 1
max_epoch: 300